GET http://localhost:3000/acciones_comunitarias
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio

###
POST http://localhost:3000/acciones_comunitarias
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
Content-Type: application/json

{
	"id_modalidad": 3,
	"objetivo_actividad": "Hacer una prueba de la tabla acciones_comunitarias",
	"no_actividades_realizadas": 5,
	"no_personas_alcanzadas": 1300,
	"info_registro": {
		"id_anio": 2,
		"id_municipio": 3,
		"id_institucion": 1,
		"registrada_por": 47,
		"mes": [
			"Enero",
			"Marzo"
		]
	},
	"poblacion": [
		"masculino 20-29",
		"femenino 20-29",
		"no binario 20-29",
		"masculino 65 y más",
		"femenino 65 y más",
		"no binario 65 y más"
	],
	"tipo_actividad": [
		"Plática/Clase",
		"Prevención"
	]
}
    
###

GET http://localhost:3000/acciones_prevencion_salud
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
###

POST http://localhost:3000/acciones_prevencion_salud
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
Content-Type: application/json

{
  "APS": "Acciones de Prevención en Salud"
}
###

GET http://localhost:3000/atencion_salud
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
###

POST http://localhost:3000/atencion_salud
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
Content-Type: application/json

{
  "APS": "Atención en Salud"
}
###

GET http://localhost:3000/capacitacion
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
###

POST http://localhost:3000/capacitacion
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
Content-Type: application/json

{
  "APS": "Capacitación"
}
###

GET http://localhost:3000/suicidio
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
###

POST http://localhost:3000/suicidio
api: 123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ5LCJyb2xlIjoyLCJpYXQiOjE2NDY2Njc1Njh9.axmr3UqzKpkJkQphLhq6z2a6gct8oV-iqbmB3KlQjio
Content-Type: application/json

{
  "APS": "Suicidio"
}
###

GET http://localhost:3000/sisma/info_registro
###
GET http://localhost:3000/sisma/modalidad
###
GET http://localhost:3000/sisma/anio
###
GET http://localhost:3000/sisma/mes
###
GET http://localhost:3000/sisma/estado
###
GET http://localhost:3000/sisma/municipio
###
GET http://localhost:3000/sisma/institucion
###
GET http://localhost:3000/sisma/poblacion
###
GET http://localhost:3000/sisma/tipo_actividad
###
GET http://localhost:3000/sisma/tipo_accion


###
GET http://localhost:3000/user
###
POST http://localhost:3000/user
api: 123
Content-Type: application/json

{
  "nombre_publico": "Capa Santa Catarina",
  "nombre_usuario": "capa",
  "password": "rufo53",
  "privilegios": 2,
  "correo": "capa@prueba.com"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "capa",
  "password": "rufo53"
}